spring.application.name=fileSystemIntegration

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/filesystemintegration
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA/Hibernation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true